version: '2'
services:

  handbrake:
    build: .
    container_name: handbrake
    restart: on-failure
    hostname: handbrake.micloud.local
    ports:
      - "8181:8181"
    volumes:
      - ./data/input:/handbrake/input:Z
      - ./data/output:/handbrake/output:Z
